name: Terraform Apply

on:
  push:
    branches:
      - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TERRAFORM_VERSION: "1.2.9"
  TF_IN_AUTOMATION: "True"

jobs:
  terraform_apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Esto asegura que todo el historial esté disponible para la detección de cambios

      - name: Detect changed folders
        id: detect-folder
        run: |
          # Listar todos los directorios que han cambiado
          FOLDERS_CHANGED=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep '/' | awk -F'/' '{print $1}' | sort -u)
          echo "Folders changed: $FOLDERS_CHANGED"
          # Asumimos que solo nos interesa el primer directorio listado
          FIRST_FOLDER=$(echo $FOLDERS_CHANGED | awk '{print $1}')
          echo "FIRST_FOLDER=$FIRST_FOLDER" >> $GITHUB_ENV
    
      - name: Use the folder name
        run: |
          echo "Changes detected in folder: $FIRST_FOLDER"

      - name: Get PR ID
        id: pr-id
        run: |
          echo "PR_NUMBER=${{ github.event.pull_request.number }}" >> $GITHUB_OUTPUT

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
          terraform_wrapper: false

      - name: Terraform Init
        id: init
        working-directory: ${{ env.FIRST_FOLDER }}/
        run: |
          export AWS_ACCESS_KEY_ID=${{ env.AWS_ACCESS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ env.AWS_SECRET_ACCESS_KEY }}
          terraform init

      - name: List files in terraform directory
        run: ls -la ${{ env.FIRST_FOLDER }}/

      - name: Terraform Plan
        id: plan
        working-directory: ${{ env.FIRST_FOLDER }}/
        run: |
          touch tfplan
          terraform plan -input=false -out=tfplan
          readlink -f tfplan

      - name: Terraform Apply
        id: apply
        working-directory: ${{ env.FIRST_FOLDER }}/
        run: |
          terraform apply -no-color tfplan
